main/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from BioEsfera.views import index,sobre_nos,jornada,jogos,perfil,cadastro,login_view,logout_view,atualizar_conquista_usuario, atualizar_avatar_usuario, login_usuario, obter_csrf_token, adicionar_conquista,atualizar_dados, conquistas, delete_user_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('Sobrenos/', sobre_nos, name='Sobrenos'),
    path('jornada/', jornada, name='jornada'),
    path('jornada/<int:jogo_id>', jogos, name='jogos'),
    path('perfil/', perfil, name='perfil'),
    path('conquistas/', conquistas, name='conquistas'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cadastro/', cadastro, name='cadastro'),
    path('delete/', delete_user_view, name='delete_user'),
    path('atualizar_conquista_usuario/<int:conquista_id>/', atualizar_conquista_usuario, name='atualizar_conquista_usuario'),
    path('atualizar_avatar/<int:avatar_id>/', atualizar_avatar_usuario, name='atualizar_avatar'),
    path('login_usuario/', login_usuario, name='login_usuario'),
    path('obter_csrf_token/', obter_csrf_token, name='obter_csrf_token'),
    path('adicionar_conquista/', adicionar_conquista, name='adicionar_conquista'),
    path('atualizar_dados/', atualizar_dados, name='atualizar_dados'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BioEsfera/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
    email = models.EmailField(max_length=150, default='Coloque_o_seu_email@email.com')
    idade = models.IntegerField(null=True, default= 18)
    sexo = models.CharField(max_length=150, blank=True, default="Outros")
    titulo_conquista = models.CharField(max_length=150, blank=True, null=True, default="Novato")
    descricao_conquista = models.CharField(max_length=150, blank=True, null=True, default="Aperte em uma conquista que você ganhou e vejá o que acontece ;)")
    avatar = models.ImageField(upload_to='images/', null=True, blank=True, default='images/cebolo_perfil.png')


    def __str__(self):
        return self.username
    
class Jogo(models.Model):
    titulo = models.CharField(max_length=150,  unique=True)
    descricao = models.TextField(max_length=1000)
    url = models.CharField(max_length=300)
    imagem = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.titulo

class Conquista(models.Model):
    titulo = models.CharField(max_length=150,  unique=True)
    descricao = models.TextField(max_length=1000)
    dica = models.TextField(max_length=1000)
    imagem = models.ImageField(upload_to='images/', null=True, blank= True)
    jogo = models.ForeignKey(Jogo, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Conquista_Usuario(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    conquista = models.ForeignKey(Conquista, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario.username} - {self.conquista.titulo}'

    class Meta: 
        unique_together = ('usuario', 'conquista')
    
class Imagem_avatar(models.Model):
    imagem = models.ImageField(upload_to='images/')
    usuario_imagem = models.ImageField(upload_to='images/')

    def __str__(self):
        return f'Avatar {self.id}'

class Usuario_avatar(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Imagem_avatar, on_delete=models.CASCADE)

BioEsfera/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class UserContCreationForm(UserCreationForm):
    SEXO_CHOICES = [ ('F','Feminino'), ('M','Masculino'), ('O','Outros'), ('N','Prefiro não dizer')]

    email = forms.EmailField(max_length=100, required=True)
    idade = forms.IntegerField(min_value=0, max_value=115)
    sexo = forms.ChoiceField(choices=SEXO_CHOICES, required=False)

    class Meta:
        model = Usuario
        fields = ('username', 'password1', 'password2', 'email', 'idade', 'sexo')

class CadastroForm(forms.ModelForm):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro')
    ]

    sexo = forms.ChoiceField(choices=SEXO_CHOICES, required=True)

    class Meta:
        model = Usuario
        fields = ['username', 'email', 'idade', 'sexo']

BioEsfera/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .models import Usuario,Jogo,Conquista,Conquista_Usuario,Imagem_avatar
from django.contrib.auth.decorators import login_required
from .forms import UserContCreationForm, CadastroForm
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.middleware.csrf import get_token
import json
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import render
from django.contrib import messages


def index(request):
    return render(request,'BioEsfera/index.html')

def sobre_nos(request):
    return render(request, 'BioEsfera/Sobrenos.html')

@login_required
def perfil(request):
    try:
        usuario = request.user
        conquistas_usuario = Conquista_Usuario.objects.filter(usuario=usuario)
        avatares = Imagem_avatar.objects.all()
        avatar_ids = list(avatares.values_list('id', flat=True))
        avatar_urls = [avatar.imagem.url for avatar in avatares]

        # Configurar a paginação
        paginator = Paginator(conquistas_usuario, 7)  # 10 conquistas por página
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'BioEsfera/perfil.html', {
            'conquistas': page_obj,
            'usuario': usuario,
            'avatar_ids': avatar_ids,
            'avatar_urls': avatar_urls,
            'page_obj': page_obj
        })

    except Usuario.DoesNotExist:
        return render(request, '404.html', {'message': 'Usuário não encontrado'})


def atualizar_conquista_usuario(request, conquista_id):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            username = data.get('username')
            
            usuario = Usuario.objects.get(username=username)
            conquista = get_object_or_404(Conquista, id=conquista_id)
            
            # Atualizar os campos titulo_conquista e descricao_conquista do usuário
            usuario.titulo_conquista = conquista.titulo
            usuario.descricao_conquista = conquista.descricao
            usuario.save()
            
            return JsonResponse({'status': 'success', 'titulo_conquista': usuario.titulo_conquista, 'descricao_conquista': usuario.descricao_conquista})
        except Usuario.DoesNotExist:
            return JsonResponse({'status': 'fail', 'error': 'Usuário não encontrado'}, status=400)
        except Conquista.DoesNotExist:
            return JsonResponse({'status': 'fail', 'error': 'Conquista não encontrada'}, status=400)
        except Exception as e:
            print(f"Erro no servidor: {e}")
            return JsonResponse({'status': 'fail', 'error': str(e)}, status=500)
    return JsonResponse({'status': 'fail', 'error': 'Invalid request method'}, status=400)


def atualizar_avatar_usuario(request, avatar_id):
    if request.method == 'POST':
        avatar = Imagem_avatar.objects.get(id=avatar_id)
        usuario = request.user
        usuario.avatar = avatar.usuario_imagem
        usuario.save()
        return JsonResponse({'status': 'success', 'avatar_url': usuario.avatar.url})
    return JsonResponse({'status': 'fail'}, status=400)

@login_required
def jornada(request):
    jogo = Jogo.objects.all()
    contexto = {
        'jogos': jogo,
    }
    return render(request, 'BioEsfera/jornada.html', contexto)

@login_required
def jogos(request, jogo_id):
    jogo_selecionado = Jogo.objects.get(id=jogo_id)
    conquista = Conquista.objects.filter(jogo = jogo_id)
    contexto ={
        'jogo': jogo_selecionado,
        'conquistas': conquista,
    }
    return render(request, 'BioEsfera/jogos.html', contexto)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)  # Loga o usuário
            return redirect('perfil')  # Redireciona para a página de perfil
        else:
            messages.error(request, 'Usuário ou senha inválidos.')

    return render(request, 'BioEsfera/login.html')

def logout_view(request):
    logout(request) 
    return redirect('login')  

def cadastro(request):
    if request.method == 'POST':
        form = UserContCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cadastro realizado com sucesso!')
            return redirect('login')
        else:
            messages.error(request, 'Por favor, corrija os erros abaixo.')
    else:
        form = UserContCreationForm()

    return render(request, 'BioEsfera/cadastro.html', {'form': form})

def delete_user_view(request):
    if request.method == 'POST':
        user = request.user
        User = get_user_model()
        try:
            User.objects.filter(id=user.id).delete()
            messages.success(request, 'Usuário deletado com sucesso.')
            return redirect('login')  # Redirecionar para a página de login após a deleção
        except Exception as e:
            messages.error(request, f'Erro ao deletar o usuário: {e}')
    return render(request, 'BioEsfera/delete_user_confirm.html')

@csrf_exempt
def login_usuario(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data.get('username')
        password = data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'fail', 'error': 'Invalid credentials'}, status=400)
    return JsonResponse({'status': 'fail', 'error': 'Invalid request method'}, status=400)

def obter_csrf_token(request):
    csrf_token = get_token(request)
    response = JsonResponse({'csrfToken': csrf_token})
    response.set_cookie('csrftoken', csrf_token)
    return response

@csrf_exempt
def adicionar_conquista(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            username = data.get('username')
            conquista_id = data.get('conquista_id')
            
            usuario = Usuario.objects.get(username=username)
            conquista = Conquista.objects.get(id=conquista_id)
            
            # Verificar se a conquista já existe para o usuário
            if Conquista_Usuario.objects.filter(usuario=usuario, conquista=conquista).exists():
                return JsonResponse({'status': 'fail', 'error': 'Conquista já adicionada para este usuário'}, status=400)
            
            Conquista_Usuario.objects.create(usuario=usuario, conquista=conquista)
            
            return JsonResponse({'status': 'success'})
        except Usuario.DoesNotExist:
            return JsonResponse({'status': 'fail', 'error': 'Usuário não encontrado'}, status=400)
        except Conquista.DoesNotExist:
            return JsonResponse({'status': 'fail', 'error': 'Conquista não encontrada'}, status=400)
        except Exception as e:
            print(f"Erro no servidor: {e}")
            return JsonResponse({'status': 'fail', 'error': str(e)}, status=500)
    return JsonResponse({'status': 'fail', 'error': 'Invalid request method'}, status=400)

@login_required
def atualizar_dados(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados atualizados com sucesso!')
        else:
            messages.error(request, 'Erro ao atualizar dados.')

    else:
        form = CadastroForm(instance=request.user)

    return render(request, 'BioEsfera/atualizar_dados.html', {'form': form})

def conquistas(request):
    conquista = Conquista.objects.all()
    contexto = {
        'conquista': conquista,
    }
    return render(request, 'BioEsfera/conquistas.html', contexto)

BioEsfera/templates/BioEsfera/Sobrenos.html
{% extends 'BioEsfera/base.html'%}
{% load static %}
{% block parte_central %}
    <link rel="stylesheet" href="{% static 'css/sobrenos.css' %}" />
    <main>
      <div id="detalheSuperior">
        <img src="{% static 'SVG/Group 97.svg' %}" alt="" />
        <h2>Sobre Nós</h2>
      </div>
      <div id="conteiner_detalheTrilha">
        <img src="{% static 'SVG/detalheDeTrilha.svg' %}" alt="" id="detalheTrilha" />

        <div class="lados ladoEsquerdo">
          <img src="{% static 'SVG/BIOESFERA_laranja.svg' %}" alt="" id="nameBio" />
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Guilherme.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto1.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-esq">Guilherme</h2>

            <p class="texto-esq">
              <span> Guilherme Vieira de Souza </span>
              é um estudante do curso de <span> informática </span> no Instituto
              Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte
              <span>(IFRN) em Pau dos Ferros</span>. Nascido em
              <span>Iracema, Ceará, em 2005</span>
              , se mudou para
              <span>Rodolfo Fernandes</span> após a 5ª série e estudou na escola
              Maria de Lourdes Cavalcante antes de ingressar no IFRN. Sua paixão
              é <span>programação</span> .
            </p>
          </div>
        </div>
        <div class="lados ladoDireito">
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Kayky.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto2.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-dir">Kayky</h2>
            <p class="texto-dir">
              <span>Kayky da Silva Batista</span>
              nasceu em
              <span>21 de setembro de 2004</span> em
              <span>Antônio Martins</span>. Sua infância foi marcada por
              <span>jogos onlines</span> que o influenciaram a seguir na
              <span>área de informática</span> no IFRN. Atualmente ele cursa o
              <span> terceiro ano de informática</span> no do campus Pau dos
              Ferros
            </p>
          </div>
        </div>

        <div class="lados ladoEsquerdo">
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Matheus.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto3.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-esq">Matheus</h2>
            <p class="texto-esq">
              <span>Matheus Rodrigues Oliveira</span> nasceu no dia
              <span>20 de abril de 2005 em Pau dos Ferros/RN</span> . Sua
              infância, assim como a de muitos, foi marcada pelos mais diversos
              <span>jogos</span>, porém seu interesse ia além do simples jogo;
              <span
                >Matheus se atraía pelos gráficos, os visuais, as mecânicas e
                lógicas</span
              >. Hoje Matheus cursa <span>informática no IFRN</span> e tem como
              <span>hobbie desenhar</span>. Ele encontrou no inocente encanto
              por gráficos de jogos uma <span>arte</span> e na curiosidade por o
              que tem por trás deles uma possível <span>carreira</span>.
            </p>
          </div>
        </div>

        <div class="lados ladoDireito">
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Raquel.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto4.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-dir">Raquel</h2>
            <p class="texto-dir">
              <span>Raquel Carlos</span> nasceu no
              <span>dia 19 de junho de 2005</span>, é natural da cidade de
              <span>Frutuoso-Gomes- RN</span> e reside lá até os dias atuais.
              Foi na cidadezinha de pouco mais de 5 mil habitantes que Raquel
              <span>aprendeu tudo que sabe hoje</span>, criou
              <span></span>memórias e desenvolveu sua paixão pelo
              <span>cinema</span> e pela <span>música</span>. No presente cursa
              <span>informática no IFRN- campus Pau dos ferros.</span>
            </p>
          </div>
        </div>

        <div class="lados ladoEsquerdo">
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Victoria.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto5.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-esq">Victória</h2>
            <p class="texto-esq">
              <span>Victória Silvina Gonçalves</span> é natural de
              <span>Pau dos Ferros, RN</span>. Atualmente cursa o
              <span>2° grau pelo IFRN-PF</span> na área da <span>TI</span>. Atua
              com crianças na igreja que congrega (Assembléia de Deus), como
              <span></span>professora e regente de conjunto. É completamente
              apaixonada por <span>música</span>, e por
              <span>instrumentos musicais</span>. Ama LIBRAS, mas ainda não sabe
              falar.
            </p>
          </div>
        </div>
        <div class="lados ladoDireito">
          <div class="conteiner-person">
            <img src="{% static 'SVG/photografh.svg' %}" alt="" class="back-img" />
            <img src="{% static 'images/Vivian.png' %}" alt="" class="person" />
            <img
              src="{% static 'SVG/arbusto6.svg' %}"
              alt=""
              class="detalhe-arbustos"
            />
          </div>
          <div class="conteiner-text">
            <h2 class="titulo-dir">Vivian</h2>
            <p class="texto-dir">
              <span>Vivian Silvina Gonçalves nasceu</span> em <span>2006</span>,
              em <span>Pau dos Ferros/RN</span>. Aluna dedicada que gosta muito
              de <span>matemática, literatura de cordel, músicas, jogos</span>,
              etc. Além disso, faz o curso de
              <span>informática pelo IFRN - Campus Pau dos Ferros</span>. Na
              igreja é regente e <span>professora do conjunto infantil</span>. É
              muito <span>curiosa</span>, e espera que essa curiosidade, junto
              com sua garra, a ajude a realizar seus
              <span>sonhos e desejos</span>.
            </p>
          </div>
        </div>
        <img
          src="{% static 'images/LOGO Verde.png' %}"
          alt=""
          style="width: 25%; position: absolute; left: 40%"
        />
        <div id="detalheInferior">
          <img src="{% static 'SVG/Group 97.svg' %}" alt="" />
        </div>
      </div>
    </main>
{% endblock %}

BioEsfera/templates/BioEsfera/atualizar_dados.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/PBioEsfera.png' %}">
    <link rel="stylesheet" href="{% static 'css/cadastro.css' %}">
  </head>
  <body>
    <header>
      <a href="{% url 'index' %}">Voltar</a>
    </header>
    <main>
      <div class="container">
        <h1>Cadastrar</h1>

        <form method="POST" id="cadastrarForm">
          {% csrf_token %}
          <div class="linha">
              <div class="label-input" style="flex:5;">
                <label for="username">nome de usuario*:</label>
                <input type="text" name="username" id="username" class="textInput" maxlength="11" value="{{ user.username }}" required>
                {% if form.username.errors %}
                    <div class="text-danger">
                        {{ form.username.errors.0 }}
                    </div>
                {% endif %}
              </div>
              <div class="label-input" style="flex:5;">
                <label for="email">E-mail:</label>
                <input type="email" name="email" id="email" class="textInput" value="{{ user.email }}" required>
                {% if form.email.errors %}
                    <div class="text-danger">
                        {{ form.email.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>
                    
          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label class="label_idade" for="idade">Idade:</label>
                <input type="text" name="idade" id="idade" class="textInput" value="{{ user.idade }}">
                {% if form.idade.errors %}
                    <div class="text-danger">
                        {{ form.idade.errors.0 }}
                    </div>
                {% endif %}
            </div>
            <div class="linha_2">
              <div class="label-input-sexo" style="flex:5;">
                  <label id="label_sexo" for="sexo">Sexo:</label>
                  <select id="id_sexo" name="sexo">
                    {% for value, display in form.sexo.field.choices %}
                      <option value="{{ value }}" {% if user.sexo == value %}selected{% endif %}>{{ display }}</option>
                    {% endfor %}
                  </select>
                  {% if form.sexo.errors %}
                      <div class="text-danger">
                          {{ form.sexo.errors.0 }}
                      </div>
                  {% endif %}
              </div>
            </div>
            <button type="submit" class="button_submit">Registrar</button>
          </div>
        </form>
      </div>
    </main>
    <script src="{% static 'javascript/btnVoltar.js' %}"></script>
    <script src="{% static 'javascript/submeter_cadastro.js' %}"></script>
  </body>
</html>

BioEsfera/templates/BioEsfera/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="icon" type="image/x-icon" href="{% static '/images/PBioEsfera.png' %}" />
    <link rel="stylesheet" href="{% static 'css/general.css' %}" />
</head>
<body>
    <header>
        <a href="{% url 'index' %}"><img src="{% static 'images/LOGO.png' %}" alt="" /></a>
        <nav>
          <ul>
            <li><a href="{% url 'index' %}">Início</a></li>
            <li><a href="{% url 'conquistas' %}">Conquistas</a></li>
            <li><a href="{% url 'jornada' %}">Jornada</a></li>
            <li><a href="{% url 'perfil' %}">Meu perfil</a></li>
            <li><a href="{% url 'Sobrenos' %}">Sobre nós</a></li>
          </ul>
        </nav>
        <div id="btnsH">
          <a id="Btn1" href="{% url 'cadastro' %}">Cadastre-se</a>
          <a id="Btn2" href="{% url 'login'%}">Entrar</a>

        </div>
      </header>

      {% block parte_central %}

      {% endblock %}

      <footer>
        <div id="borderFoo">
          <img src="{% static '/images/LOGO2.png' %}" alt="" />
        </div>
        <div id="listFoo">
          <ul>
            <li><a href="{% url 'Sobrenos' %}">Sobre nós</a></li>
            <li><a href="">Contatos</a></li>
            <li><a href="Mailto:feedbackobioesfera@gmail.com">Feedback</a></li>
            <li><a href="">Sobre Projeto</a></li>
            <li><a href="">Redes Sociais</a></li>
          </ul>
        </div>
      </footer>
</body>
</html>

BioEsfera/templates/BioEsfera/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadastro</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/PBioEsfera.png' %}">
    <link rel="stylesheet" href="{% static 'css/general.css' %}">
    <link rel="stylesheet" href="{% static 'css/cadastro.css' %}" />
  </head>
  <body>
    <header>
      <button id="BtnV">Voltar</button>
    </header>
    <main>
      <div class="container">
        <h1>Cadastrar</h1>

        <form method="POST" id="cadastrarForm">
          {% csrf_token %}
          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label for="username">nome de usuario:</label>
                <input type="text" name="username" id="username" class="textInput" maxlength="11" required>
                {% if form.username.errors %}
                    <div class="text-danger">
                        {{ form.username.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>
          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label for="password1">Senha*:</label>
                <input type="password" name="password1" id="password1" class="textInput" required>
                {% if form.password1.errors %}
                    <div class="text-danger">
                        {{ form.password1.errors.0 }}
                    </div>
                {% endif %}
          </div>
          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label for="password2">Confirme a Senha</label>
                <input type="password" name="password2" id="password2" class="textInput" required>
                {% if form.password2.errors %}
                    <div class="text-danger">
                        {{ form.password2.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>
          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label for="email">E-mail</label>
                <input type="email" name="email" id="email" class="textInput" required>
                {% if form.email.errors %}
                    <div class="text-danger">
                        {{ form.email.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>
                    
          <div class="linha"></div>
            <div class="label-input" style="flex:5;">
                <label for="idade">Idade</label>
                <input type="text" name="idade" id="idade" class="textInput">
                {% if form.idade.errors %}
                    <div class="text-danger">
                        {{ form.idade.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>

          <div class="linha">
            <div class="label-input" style="flex:5;">
                <label for="sexo">Sexo:</label>
                <select id="id_sexo" name="sexo">
                  {% for value, display in form.sexo.field.choices %}
                      <option value="{{ value }}" {% if form.sexo.value == value %}selected {% endif %}>{{ display }}<option>
                  {% endfor %}
                </select>
                {% if form.sexo.errors %}
                    <div class="text-danger">
                        {{ form.sexo.errors.0 }}
                    </div>
                {% endif %}
            </div>
          </div>
          <button type="submit" class="btn btn-primary btn-block">Registrar</button>
        </form>
      </div>
    </main>
    <script src="{% static 'javascript/btnVoltar.js' %}"></script>
    <script src="{% static 'javascript/submeter_cadastro.js' %}"></script>
  </body>
</html>

BioEsfera/templates/BioEsfera/conquistas.html
{% extends 'BioEsfera/base.html'%}
{% load static %}
{% block parte_central %}
  <link rel="stylesheet" href="{% static 'css/conquistas.css' %}" />
  <main>
    <div class="div_borderFoo"><p class="p_medalhas">MEDALHAS</p></div>
    <div class="div_conquistas">
      {% for conquista in conquista %}
        <div class="div_medalhas">
          <img class="img_conquista" src={{conquista.imagem.url}}>
          <p class="p_titulo">{{conquista.titulo}}</p>
          <p class="p_dica">{{conquista.dica}}</p>
        </div>
      {% endfor %}
    </div>
  </main>



{%endblock%}